services:
  frontend:
    build:
      context: ./frontend  # The path to your frontend Dockerfile (React app)
    ports:
      - "8003:3000"        # Map host port 3000 to container port 3000 for frontend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000  # Set backend URL for React app
    networks:
      - my-shared-network

networks:
  my-shared-network:
    driver: bridge